version: "3"

tasks:
  docker.up:
    desc: Starts the docker containers
    aliases:
      - up
    cmds:
      - docker compose up -d
  docker.down:
    desc: Stops the docker containers
    aliases:
      - down
    cmds:
      - docker compose down
  docker.restart:
    desc: Restarts the docker containers
    aliases:
      - restart
    cmds:
      - docker compose down && docker compose up -d