import { validateAppwriteEnv } from '@repo/appwrite-core';
import type { HomeData } from '@repo/appwrite-core/domain';
import { AppwriteProvider, CmsService } from '@repo/appwrite-core/server';
import dotenv from 'dotenv';

dotenv.config();

async function seed() {
  console.log('🌱 Seeding Appwrite CMS with mock data...');

  try {
    const config = validateAppwriteEnv(
      process.env as Record<string, string | undefined>,
    );

    AppwriteProvider.initialize(config);
    const service = new CmsService(
      AppwriteProvider.client,
      config.APPWRITE_DATABASE_ID,
      ['en', 'pt'],
    );

    console.log('  Seeding Metric Sources...');
    const sources = await service.saveMetricSources([
      {
        id: '',
        name: 'Manual Input',
        type: 'manual',
        iconCode: 'lucide:edit',
        status: 'active',
      },
      {
        id: '',
        name: 'GitHub',
        type: 'automated',
        iconCode: 'lucide:github',
        functionId: 'fn-telemetry',
        status: 'active',
      },
      {
        id: '',
        name: 'Appwrite',
        type: 'automated',
        iconCode: 'lucide:database',
        functionId: 'fn-appwrite',
        status: 'active',
      },
    ]);

    const manualSource = sources.find((s) => s.type === 'manual');
    if (!manualSource) {
      throw new Error(
        'Critical Error: "Manual Input" source not found after creation.',
      );
    }
    const manualSourceId = manualSource.id;

    const locales = ['en', 'pt'];

    for (const locale of locales) {
      console.log(`  [${locale}] Seeding Home...`);
      const homeData: Omit<HomeData, 'id'> = {
        firstName: 'Tiago',
        lastName: 'Poli',
        namePresentation:
          locale === 'en' ? 'Tiago Poli / Architect' : 'Tiago Poli / Arquiteto',
        title:
          locale === 'en'
            ? 'Crafting Antigravity Code'
            : 'Codificando em Antigravidade',
        description:
          locale === 'en'
            ? 'Fullstack developer specialized in high-fidelity systems.'
            : 'Desenvolvedor Fullstack especializado em sistemas de alta fidelidade.',
        downloadButtonText:
          locale === 'en' ? 'Download Resume' : 'Baixar Currículo',
        journeyStartedIn: 2018,
        locale,
        pictureId: '',
        cvId: '',
      };
      await service.saveHome(locale, homeData);

      await service.saveAbout(locale, {
        locale,
        content:
          locale === 'en'
            ? 'I am a software engineer specializing in high-fidelity, monorepo architectures and elite developer experiences. With 5+ years of experience, I architect solutions that transcend the ordinary.'
            : 'Eu sou um engenheiro de software especializado em arquiteturas monorepo de alta fidelidade e experiências de desenvolvedor de elite. Com mais de 5 anos de experiência, projeto soluções que transcendem o ordinário.',
        metrics: [
          {
            id: '', // Will be generated by repo
            aboutId: '', // Will be set by service/repo
            internalCode: 'lines-of-code',
            locale,
            label: 'Lines of Code',
            value: '1M+',
            sourceId: manualSourceId,
            isPlaceholder: false,
          },
          {
            id: '',
            aboutId: '',
            internalCode: 'coffee-cups',
            locale,
            label: 'Coffee Cups',
            value: '500+',
            sourceId: manualSourceId,
            isPlaceholder: false,
          },
        ],
      });

      console.log(`  [${locale}] Seeding History (Experience)...`);
      await service.saveHistory('experience', locale, [
        {
          id: '',
          locale,
          type: 'experience',
          title: locale === 'en' ? 'Senior Architect' : 'Arquiteto Sênior',
          organization: 'Vertex Corp',
          location: 'Remote',
          period: '2021 — Present',
          description: 'Leading global infrastructure and AI orchestration.',
          current: true,
          sort: 0,
        },
      ]);

      console.log(`  [${locale}] Seeding History (Education)...`);
      await service.saveHistory('education', locale, [
        {
          id: '',
          locale,
          type: 'education',
          title: locale === 'en' ? 'Computer Science' : 'Ciência da Computação',
          organization: 'Tech University',
          location: 'São Paulo, BR',
          period: '2014 — 2018',
          description: 'Focus on distributed systems and software engineering.',
          current: false,
          sort: 0,
        },
      ]);

      console.log(`  [${locale}] Seeding Skills...`);
      await service.saveSkills(locale, [
        {
          id: '',
          title: 'React',
          type: 'frontend',
          sort: 0,
          iconCode: 'lucide:code',
          status: 'active',
        },
        {
          id: '',
          title: 'Node.js',
          type: 'backend',
          sort: 1,
          iconCode: 'lucide:server',
          status: 'active',
        },
      ]);
    }

    console.log('✅ Seeding Complete!');
  } catch (error) {
    console.error('❌ Seeding Failed:', error);
    process.exit(1);
  }
}

seed();
