/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortfolioCmsRouteImport } from './routes/portfolio-cms'
import { Route as ConnectionLostRouteImport } from './routes/connection-lost'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioCmsIndexRouteImport } from './routes/portfolio-cms/index'
import { Route as PortfolioCmsSolutionsRouteImport } from './routes/portfolio-cms/solutions'
import { Route as PortfolioCmsSkillsRouteImport } from './routes/portfolio-cms/skills'
import { Route as PortfolioCmsHomeRouteImport } from './routes/portfolio-cms/home'
import { Route as PortfolioCmsExperienceRouteImport } from './routes/portfolio-cms/experience'
import { Route as PortfolioCmsEducationRouteImport } from './routes/portfolio-cms/education'
import { Route as PortfolioCmsContactRouteImport } from './routes/portfolio-cms/contact'
import { Route as PortfolioCmsAboutRouteImport } from './routes/portfolio-cms/about'
import { Route as ErrorStartupRouteImport } from './routes/error/startup'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioCmsRoute = PortfolioCmsRouteImport.update({
  id: '/portfolio-cms',
  path: '/portfolio-cms',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionLostRoute = ConnectionLostRouteImport.update({
  id: '/connection-lost',
  path: '/connection-lost',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioCmsIndexRoute = PortfolioCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioCmsRoute,
} as any)
const PortfolioCmsSolutionsRoute = PortfolioCmsSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => PortfolioCmsRoute,
} as any)
const PortfolioCmsSkillsRoute = PortfolioCmsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => PortfolioCmsRoute,
} as any)
const PortfolioCmsHomeRoute = PortfolioCmsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PortfolioCmsRoute,
} as any)
const PortfolioCmsExperienceRoute = PortfolioCmsExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => PortfolioCmsRoute,
} as any)
const PortfolioCmsEducationRoute = PortfolioCmsEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => PortfolioCmsRoute,
} as any)
const PortfolioCmsContactRoute = PortfolioCmsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PortfolioCmsRoute,
} as any)
const PortfolioCmsAboutRoute = PortfolioCmsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PortfolioCmsRoute,
} as any)
const ErrorStartupRoute = ErrorStartupRouteImport.update({
  id: '/error/startup',
  path: '/error/startup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connection-lost': typeof ConnectionLostRoute
  '/portfolio-cms': typeof PortfolioCmsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/error/startup': typeof ErrorStartupRoute
  '/portfolio-cms/about': typeof PortfolioCmsAboutRoute
  '/portfolio-cms/contact': typeof PortfolioCmsContactRoute
  '/portfolio-cms/education': typeof PortfolioCmsEducationRoute
  '/portfolio-cms/experience': typeof PortfolioCmsExperienceRoute
  '/portfolio-cms/home': typeof PortfolioCmsHomeRoute
  '/portfolio-cms/skills': typeof PortfolioCmsSkillsRoute
  '/portfolio-cms/solutions': typeof PortfolioCmsSolutionsRoute
  '/portfolio-cms/': typeof PortfolioCmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connection-lost': typeof ConnectionLostRoute
  '/settings': typeof SettingsRoute
  '/error/startup': typeof ErrorStartupRoute
  '/portfolio-cms/about': typeof PortfolioCmsAboutRoute
  '/portfolio-cms/contact': typeof PortfolioCmsContactRoute
  '/portfolio-cms/education': typeof PortfolioCmsEducationRoute
  '/portfolio-cms/experience': typeof PortfolioCmsExperienceRoute
  '/portfolio-cms/home': typeof PortfolioCmsHomeRoute
  '/portfolio-cms/skills': typeof PortfolioCmsSkillsRoute
  '/portfolio-cms/solutions': typeof PortfolioCmsSolutionsRoute
  '/portfolio-cms': typeof PortfolioCmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connection-lost': typeof ConnectionLostRoute
  '/portfolio-cms': typeof PortfolioCmsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/error/startup': typeof ErrorStartupRoute
  '/portfolio-cms/about': typeof PortfolioCmsAboutRoute
  '/portfolio-cms/contact': typeof PortfolioCmsContactRoute
  '/portfolio-cms/education': typeof PortfolioCmsEducationRoute
  '/portfolio-cms/experience': typeof PortfolioCmsExperienceRoute
  '/portfolio-cms/home': typeof PortfolioCmsHomeRoute
  '/portfolio-cms/skills': typeof PortfolioCmsSkillsRoute
  '/portfolio-cms/solutions': typeof PortfolioCmsSolutionsRoute
  '/portfolio-cms/': typeof PortfolioCmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connection-lost'
    | '/portfolio-cms'
    | '/settings'
    | '/error/startup'
    | '/portfolio-cms/about'
    | '/portfolio-cms/contact'
    | '/portfolio-cms/education'
    | '/portfolio-cms/experience'
    | '/portfolio-cms/home'
    | '/portfolio-cms/skills'
    | '/portfolio-cms/solutions'
    | '/portfolio-cms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connection-lost'
    | '/settings'
    | '/error/startup'
    | '/portfolio-cms/about'
    | '/portfolio-cms/contact'
    | '/portfolio-cms/education'
    | '/portfolio-cms/experience'
    | '/portfolio-cms/home'
    | '/portfolio-cms/skills'
    | '/portfolio-cms/solutions'
    | '/portfolio-cms'
  id:
    | '__root__'
    | '/'
    | '/connection-lost'
    | '/portfolio-cms'
    | '/settings'
    | '/error/startup'
    | '/portfolio-cms/about'
    | '/portfolio-cms/contact'
    | '/portfolio-cms/education'
    | '/portfolio-cms/experience'
    | '/portfolio-cms/home'
    | '/portfolio-cms/skills'
    | '/portfolio-cms/solutions'
    | '/portfolio-cms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionLostRoute: typeof ConnectionLostRoute
  PortfolioCmsRoute: typeof PortfolioCmsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ErrorStartupRoute: typeof ErrorStartupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-cms': {
      id: '/portfolio-cms'
      path: '/portfolio-cms'
      fullPath: '/portfolio-cms'
      preLoaderRoute: typeof PortfolioCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection-lost': {
      id: '/connection-lost'
      path: '/connection-lost'
      fullPath: '/connection-lost'
      preLoaderRoute: typeof ConnectionLostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-cms/': {
      id: '/portfolio-cms/'
      path: '/'
      fullPath: '/portfolio-cms/'
      preLoaderRoute: typeof PortfolioCmsIndexRouteImport
      parentRoute: typeof PortfolioCmsRoute
    }
    '/portfolio-cms/solutions': {
      id: '/portfolio-cms/solutions'
      path: '/solutions'
      fullPath: '/portfolio-cms/solutions'
      preLoaderRoute: typeof PortfolioCmsSolutionsRouteImport
      parentRoute: typeof PortfolioCmsRoute
    }
    '/portfolio-cms/skills': {
      id: '/portfolio-cms/skills'
      path: '/skills'
      fullPath: '/portfolio-cms/skills'
      preLoaderRoute: typeof PortfolioCmsSkillsRouteImport
      parentRoute: typeof PortfolioCmsRoute
    }
    '/portfolio-cms/home': {
      id: '/portfolio-cms/home'
      path: '/home'
      fullPath: '/portfolio-cms/home'
      preLoaderRoute: typeof PortfolioCmsHomeRouteImport
      parentRoute: typeof PortfolioCmsRoute
    }
    '/portfolio-cms/experience': {
      id: '/portfolio-cms/experience'
      path: '/experience'
      fullPath: '/portfolio-cms/experience'
      preLoaderRoute: typeof PortfolioCmsExperienceRouteImport
      parentRoute: typeof PortfolioCmsRoute
    }
    '/portfolio-cms/education': {
      id: '/portfolio-cms/education'
      path: '/education'
      fullPath: '/portfolio-cms/education'
      preLoaderRoute: typeof PortfolioCmsEducationRouteImport
      parentRoute: typeof PortfolioCmsRoute
    }
    '/portfolio-cms/contact': {
      id: '/portfolio-cms/contact'
      path: '/contact'
      fullPath: '/portfolio-cms/contact'
      preLoaderRoute: typeof PortfolioCmsContactRouteImport
      parentRoute: typeof PortfolioCmsRoute
    }
    '/portfolio-cms/about': {
      id: '/portfolio-cms/about'
      path: '/about'
      fullPath: '/portfolio-cms/about'
      preLoaderRoute: typeof PortfolioCmsAboutRouteImport
      parentRoute: typeof PortfolioCmsRoute
    }
    '/error/startup': {
      id: '/error/startup'
      path: '/error/startup'
      fullPath: '/error/startup'
      preLoaderRoute: typeof ErrorStartupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortfolioCmsRouteChildren {
  PortfolioCmsAboutRoute: typeof PortfolioCmsAboutRoute
  PortfolioCmsContactRoute: typeof PortfolioCmsContactRoute
  PortfolioCmsEducationRoute: typeof PortfolioCmsEducationRoute
  PortfolioCmsExperienceRoute: typeof PortfolioCmsExperienceRoute
  PortfolioCmsHomeRoute: typeof PortfolioCmsHomeRoute
  PortfolioCmsSkillsRoute: typeof PortfolioCmsSkillsRoute
  PortfolioCmsSolutionsRoute: typeof PortfolioCmsSolutionsRoute
  PortfolioCmsIndexRoute: typeof PortfolioCmsIndexRoute
}

const PortfolioCmsRouteChildren: PortfolioCmsRouteChildren = {
  PortfolioCmsAboutRoute: PortfolioCmsAboutRoute,
  PortfolioCmsContactRoute: PortfolioCmsContactRoute,
  PortfolioCmsEducationRoute: PortfolioCmsEducationRoute,
  PortfolioCmsExperienceRoute: PortfolioCmsExperienceRoute,
  PortfolioCmsHomeRoute: PortfolioCmsHomeRoute,
  PortfolioCmsSkillsRoute: PortfolioCmsSkillsRoute,
  PortfolioCmsSolutionsRoute: PortfolioCmsSolutionsRoute,
  PortfolioCmsIndexRoute: PortfolioCmsIndexRoute,
}

const PortfolioCmsRouteWithChildren = PortfolioCmsRoute._addFileChildren(
  PortfolioCmsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionLostRoute: ConnectionLostRoute,
  PortfolioCmsRoute: PortfolioCmsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ErrorStartupRoute: ErrorStartupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
