/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ConnectionLostRouteImport } from './routes/connection-lost'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrorStartupRouteImport } from './routes/error/startup'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionLostRoute = ConnectionLostRouteImport.update({
  id: '/connection-lost',
  path: '/connection-lost',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorStartupRoute = ErrorStartupRouteImport.update({
  id: '/error/startup',
  path: '/error/startup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connection-lost': typeof ConnectionLostRoute
  '/settings': typeof SettingsRoute
  '/error/startup': typeof ErrorStartupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connection-lost': typeof ConnectionLostRoute
  '/settings': typeof SettingsRoute
  '/error/startup': typeof ErrorStartupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connection-lost': typeof ConnectionLostRoute
  '/settings': typeof SettingsRoute
  '/error/startup': typeof ErrorStartupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connection-lost' | '/settings' | '/error/startup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connection-lost' | '/settings' | '/error/startup'
  id: '__root__' | '/' | '/connection-lost' | '/settings' | '/error/startup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionLostRoute: typeof ConnectionLostRoute
  SettingsRoute: typeof SettingsRoute
  ErrorStartupRoute: typeof ErrorStartupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection-lost': {
      id: '/connection-lost'
      path: '/connection-lost'
      fullPath: '/connection-lost'
      preLoaderRoute: typeof ConnectionLostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/startup': {
      id: '/error/startup'
      path: '/error/startup'
      fullPath: '/error/startup'
      preLoaderRoute: typeof ErrorStartupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionLostRoute: ConnectionLostRoute,
  SettingsRoute: SettingsRoute,
  ErrorStartupRoute: ErrorStartupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
