name: Build and Tag Static Files

on:
  push:
    tags:
      - "*" # Trigger on all new tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'

      # Step 3: Install dependencies with Yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Build the Vite app
      - name: Build Vite app
        run: yarn build

      # Step 5: Commit and push the static files to the tag
      - name: Commit and push built files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "Add static files for tag $GITHUB_REF"
          git push origin HEAD:$GITHUB_REF
