name: Build and Tag Static Files

on:
  push:
    tags:
      - "*" # Trigger on all new tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'

      # Step 3: Install dependencies with Yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Build the Vite app
      - name: Build Vite app
        run: yarn build

      # Step 5: zip the dist folder
      - name: Zip dist folder
        run: zip -r dist.zip dist

      # Step 6: Upload the zipped dist folder storage
      - name: Upload to MinIO
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.STORAGE_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STORAGE_SECRET_KEY }}
        run: |
          aws s3 cp dist.zip s3://portifolio/dist.zip \
            --endpoint-url https://storage.lunalabs.com.br
